"""add leads table and lead permissions

Revision ID: 0701461178f7
Revises: 469336338eff
Create Date: 2026-07-16 21:25:14.627816

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0701461178f7'
down_revision: Union[str, Sequence[str], None] = '469336338eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The specific delta this migration adds, frozen at the time it was
# written — deliberately *not* imported from
# `infrastructure.database.seed_data`, whose PERMISSIONS/ROLE_PERMISSIONS
# keep growing in later phases. Importing the live (future) lists here
# would make this migration's behavior depend on code that doesn't exist
# yet when this migration actually runs against a real database.
_NEW_PERMISSIONS: list[tuple[str, str]] = [
    ("leads.read", "View leads"),
    ("leads.manage", "Update lead status and assignment"),
]
_NEW_ROLE_PERMISSIONS: dict[str, list[str]] = {
    "admin": ["leads.read", "leads.manage"],
    "employee": ["leads.read", "leads.manage"],
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('contact_submission_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'converted', 'disqualified', name='lead_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_submission_id'], ['contact_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_submission_id')
    )
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###

    _seed_lead_permissions()


def _seed_lead_permissions() -> None:
    bind = op.get_bind()

    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("description", sa.String()),
    )
    roles_table = sa.table("roles", sa.column("id", sa.Uuid()), sa.column("name", sa.String()))
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.Uuid()),
        sa.column("permission_id", sa.Uuid()),
    )

    permission_ids = {code: uuid.uuid4() for code, _ in _NEW_PERMISSIONS}
    op.bulk_insert(
        permissions_table,
        [
            {"id": permission_ids[code], "code": code, "description": description}
            for code, description in _NEW_PERMISSIONS
        ],
    )

    role_ids = {
        row.name: row.id
        for row in bind.execute(
            sa.select(roles_table.c.id, roles_table.c.name).where(
                roles_table.c.name.in_(_NEW_ROLE_PERMISSIONS)
            )
        ).fetchall()
    }

    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": role_ids[role_name], "permission_id": permission_ids[code]}
            for role_name, codes in _NEW_ROLE_PERMISSIONS.items()
            for code in codes
            if role_name in role_ids
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # role_permissions rows cascade-delete with their permission (see the
    # ondelete='CASCADE' FK from Phase 2's migration).
    permissions_table = sa.table(
        "permissions", sa.column("id", sa.Uuid()), sa.column("code", sa.String())
    )
    codes = [code for code, _ in _NEW_PERMISSIONS]
    op.execute(permissions_table.delete().where(permissions_table.c.code.in_(codes)))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
    # As in Phase 1/2's migrations: dropping the table doesn't drop the
    # native Postgres enum type it created, which otherwise breaks a
    # subsequent downgrade -> upgrade cycle.
    sa.Enum(name='lead_status').drop(op.get_bind(), checkfirst=True)
