"""add LOS: loan applications and documents

Revision ID: 5bf4ba328030
Revises: c7c3ce2e47cc
Create Date: 2026-07-16 23:06:05.755708

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf4ba328030'
down_revision: Union[str, Sequence[str], None] = 'c7c3ce2e47cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Frozen at the time this migration was written — not imported from
# `infrastructure.database.seed_data`. See migration c422da52af08's own
# comment (and Phase 5's `0701461178f7`, which found the bug this
# pattern avoids): that module's lists keep growing in later phases, and
# importing it here would make a fresh `alembic upgrade head` re-seed
# whatever seed_data.py looks like *today* and collide with this
# migration's own inserts.
_NEW_PERMISSIONS: list[tuple[str, str]] = [
    ("loans.read", "View loan applications, documents, and analytics"),
    ("loans.manage", "Review, approve, sanction, disburse, and close loan applications"),
]
_NEW_ROLE_PERMISSIONS: dict[str, list[str]] = {
    "admin": ["loans.read", "loans.manage"],
    "employee": ["loans.read", "loans.manage"],
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_applications',
    sa.Column('customer_user_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('loan_product_slug', sa.String(length=100), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=False),
    sa.Column('existing_monthly_obligations', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'approved', 'rejected', 'sanctioned', 'disbursed', 'closed', 'withdrawn', name='loan_application_status'), nullable=False),
    sa.Column('kyc_status', sa.Enum('pending', 'verified', 'rejected', name='kyc_status'), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verification_status'), nullable=False),
    sa.Column('eligibility_status', sa.Enum('pending', 'eligible', 'ineligible', name='eligibility_status'), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('risk_category', sa.Enum('low', 'medium', 'high', name='risk_category'), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('sanctioned_amount', sa.Integer(), nullable=True),
    sa.Column('sanctioned_tenure_months', sa.Integer(), nullable=True),
    sa.Column('sanction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disbursed_amount', sa.Integer(), nullable=True),
    sa.Column('disbursement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disbursement_reference', sa.String(length=100), nullable=True),
    sa.Column('commission_amount', sa.Integer(), nullable=True),
    sa.Column('commission_status', sa.Enum('pending', 'approved', 'paid', name='commission_status'), nullable=True),
    sa.Column('closure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_assigned_to'), 'loan_applications', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_loan_applications_customer_user_id'), 'loan_applications', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_status'), 'loan_applications', ['status'], unique=False)
    op.create_table('loan_documents',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'submitted', 'verified', 'rejected', name='loan_document_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_documents_application_id'), 'loan_documents', ['application_id'], unique=False)
    # ### end Alembic commands ###

    _seed_loan_permissions()


def _seed_loan_permissions() -> None:
    bind = op.get_bind()

    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("description", sa.String()),
    )
    roles_table = sa.table("roles", sa.column("id", sa.Uuid()), sa.column("name", sa.String()))
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.Uuid()),
        sa.column("permission_id", sa.Uuid()),
    )

    permission_ids = {code: uuid.uuid4() for code, _ in _NEW_PERMISSIONS}
    op.bulk_insert(
        permissions_table,
        [
            {"id": permission_ids[code], "code": code, "description": description}
            for code, description in _NEW_PERMISSIONS
        ],
    )

    role_ids = {
        row.name: row.id
        for row in bind.execute(
            sa.select(roles_table.c.id, roles_table.c.name).where(
                roles_table.c.name.in_(_NEW_ROLE_PERMISSIONS)
            )
        ).fetchall()
    }

    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": role_ids[role_name], "permission_id": permission_ids[code]}
            for role_name, codes in _NEW_ROLE_PERMISSIONS.items()
            for code in codes
            if role_name in role_ids
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    permissions_table = sa.table(
        "permissions", sa.column("id", sa.Uuid()), sa.column("code", sa.String())
    )
    codes = [code for code, _ in _NEW_PERMISSIONS]
    op.execute(permissions_table.delete().where(permissions_table.c.code.in_(codes)))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_documents_application_id'), table_name='loan_documents')
    op.drop_table('loan_documents')
    op.drop_index(op.f('ix_loan_applications_status'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_customer_user_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_assigned_to'), table_name='loan_applications')
    op.drop_table('loan_applications')
    # ### end Alembic commands ###
    # As in earlier migrations: dropping the tables doesn't drop the
    # native Postgres enum types they created.
    for enum_name in (
        "loan_document_status",
        "commission_status",
        "risk_category",
        "eligibility_status",
        "verification_status",
        "kyc_status",
        "loan_application_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
