"""add CRM: customer profiles, tags, interactions

Revision ID: c7c3ce2e47cc
Revises: db0c83879dfe
Create Date: 2026-07-16 22:32:44.631366

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c3ce2e47cc'
down_revision: Union[str, Sequence[str], None] = 'db0c83879dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Frozen at the time this migration was written — not imported from
# `infrastructure.database.seed_data`. See migration c422da52af08's own
# comment for why: that module's lists keep growing in later phases, and
# importing the live module here would make a fresh `alembic upgrade
# head` re-seed whatever seed_data.py looks like *today* and collide with
# this migration's own inserts (exactly the bug Phase 5 found and fixed).
_NEW_PERMISSIONS: list[tuple[str, str]] = [
    ("customers.read", "View customer profiles, interactions, and analytics"),
    ("customers.manage", "Update customer segment, tags, relationship manager, and interactions"),
]
_NEW_ROLE_PERMISSIONS: dict[str, list[str]] = {
    "admin": ["customers.read", "customers.manage"],
    "employee": ["customers.read", "customers.manage"],
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_manager_id', sa.Uuid(), nullable=True),
    sa.Column('segment', sa.Enum('new', 'active', 'high_value', 'at_risk', 'dormant', name='customer_segment'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_customer_profiles_relationship_manager_id'), 'customer_profiles', ['relationship_manager_id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_segment'), 'customer_profiles', ['segment'], unique=False)
    op.create_table('interactions',
    sa.Column('customer_user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('call', 'email', 'whatsapp', 'meeting', 'note', name='interaction_channel'), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='interaction_direction'), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logged_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_channel'), 'interactions', ['channel'], unique=False)
    op.create_index(op.f('ix_interactions_customer_user_id'), 'interactions', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_interactions_occurred_at'), 'interactions', ['occurred_at'], unique=False)
    op.create_table('customer_tags',
    sa.Column('customer_profile_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_profile_id', 'tag_id')
    )
    # ### end Alembic commands ###

    _seed_customer_permissions()


def _seed_customer_permissions() -> None:
    bind = op.get_bind()

    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("description", sa.String()),
    )
    roles_table = sa.table("roles", sa.column("id", sa.Uuid()), sa.column("name", sa.String()))
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.Uuid()),
        sa.column("permission_id", sa.Uuid()),
    )

    permission_ids = {code: uuid.uuid4() for code, _ in _NEW_PERMISSIONS}
    op.bulk_insert(
        permissions_table,
        [
            {"id": permission_ids[code], "code": code, "description": description}
            for code, description in _NEW_PERMISSIONS
        ],
    )

    role_ids = {
        row.name: row.id
        for row in bind.execute(
            sa.select(roles_table.c.id, roles_table.c.name).where(
                roles_table.c.name.in_(_NEW_ROLE_PERMISSIONS)
            )
        ).fetchall()
    }

    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": role_ids[role_name], "permission_id": permission_ids[code]}
            for role_name, codes in _NEW_ROLE_PERMISSIONS.items()
            for code in codes
            if role_name in role_ids
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    permissions_table = sa.table(
        "permissions", sa.column("id", sa.Uuid()), sa.column("code", sa.String())
    )
    codes = [code for code, _ in _NEW_PERMISSIONS]
    op.execute(permissions_table.delete().where(permissions_table.c.code.in_(codes)))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_tags')
    op.drop_index(op.f('ix_interactions_occurred_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_customer_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_channel'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_customer_profiles_segment'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_relationship_manager_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
    # As in earlier migrations: dropping the tables doesn't drop the
    # native Postgres enum types they created.
    sa.Enum(name='interaction_direction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interaction_channel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='customer_segment').drop(op.get_bind(), checkfirst=True)
