"""add lead sources, tasks, and analytics support

Revision ID: db0c83879dfe
Revises: 0701461178f7
Create Date: 2026-07-16 21:52:07.230439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0c83879dfe'
down_revision: Union[str, Sequence[str], None] = '0701461178f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_tasks',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'cancelled', name='lead_task_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_tasks_assigned_to'), 'lead_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_lead_tasks_due_at'), 'lead_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_lead_tasks_lead_id'), 'lead_tasks', ['lead_id'], unique=False)
    # server_default backfills existing rows (every lead before this
    # migration came from the contact form — import didn't exist yet),
    # then gets dropped so it doesn't linger: new rows always specify
    # `source` explicitly via the ORM's Python-side default, matching how
    # every other enum column on this table already behaves.
    # Unlike create_table, add_column doesn't implicitly CREATE TYPE.
    lead_source_enum = sa.Enum('contact_form', 'manual', name='lead_source')
    lead_source_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'leads',
        sa.Column(
            'source',
            lead_source_enum,
            nullable=False,
            server_default='contact_form',
        ),
    )
    op.alter_column('leads', 'source', server_default=None)
    op.alter_column('leads', 'contact_submission_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'contact_submission_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('leads', 'source')
    op.drop_index(op.f('ix_lead_tasks_lead_id'), table_name='lead_tasks')
    op.drop_index(op.f('ix_lead_tasks_due_at'), table_name='lead_tasks')
    op.drop_index(op.f('ix_lead_tasks_assigned_to'), table_name='lead_tasks')
    op.drop_table('lead_tasks')
    # ### end Alembic commands ###
    # As in earlier migrations: dropping the column/table doesn't drop the
    # native Postgres enum types they created.
    sa.Enum(name='lead_task_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='lead_source').drop(op.get_bind(), checkfirst=True)
